language: node_js
node_js:
  - 10

before_install:
  - test/web-platform-tests/tests/wpt make-hosts-file | sudo tee -a /etc/hosts

install:
  - yarn --frozen-lockfile

script:
  - yarn lint
  - yarn test --retries 1
